# Generated by Django 4.1.3 on 2022-12-28 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databases', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryagent',
            name='DL_no',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='payment',
            name='Satus',
            field=models.IntegerField(choices=[(1, 'Paid'), (2, 'Not paid')]),
        ),
    ]
