# Generated by Django 4.0.2 on 2023-01-02 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('databases', '0002_alter_deliveryagent_dl_no_alter_payment_satus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='Role_Id',
        ),
    ]
