# Generated by Django 4.1.3 on 2022-12-30 07:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('databases', '0002_alter_deliveryagent_dl_no_alter_payment_satus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='Role_Id',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='Photo',
            field=models.ImageField(default=django.utils.timezone.now, upload_to=''),
            preserve_default=False,
        ),
    ]
