# Generated by Django 4.0.2 on 2023-01-10 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databases', '0002_rename_first_name_useraccount_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='role',
            field=models.IntegerField(default=False),
        ),
    ]
