# Generated by Django 4.0.2 on 2023-01-02 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('databases', '0003_remove_restaurant_role_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='Role_Id',
        ),
        migrations.RemoveField(
            model_name='deliveryagent',
            name='Role_Id',
        ),
    ]
