# Generated by Django 4.1.3 on 2022-12-30 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('databases', '0003_remove_restaurant_role_id_restaurant_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='Photo',
        ),
    ]
