# Generated by Django 4.1.3 on 2022-12-30 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databases', '0004_remove_restaurant_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='Mgr_no',
            field=models.CharField(max_length=100),
        ),
    ]
