# Generated by Django 4.0.2 on 2023-01-02 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databases', '0004_remove_customer_role_id_remove_deliveryagent_role_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='Name',
            field=models.CharField(default='NULL', max_length=100),
        ),
    ]
