# Generated by Django 4.0.2 on 2023-01-14 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('databases', '0008_useraccount_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='name',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='role',
        ),
    ]
