# Generated by Django 4.0.2 on 2023-01-14 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databases', '0009_remove_useraccount_name_remove_useraccount_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='name',
            field=models.CharField(default='xyz', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='useraccount',
            name='role',
            field=models.CharField(default=False, max_length=255),
        ),
    ]
