# Generated by Django 4.0.2 on 2023-01-19 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('databases', '0011_remove_useraccount_name_remove_useraccount_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='Photo',
        ),
    ]
