# Generated by Django 4.0.2 on 2023-01-21 18:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('databases', '0015_remove_cart_amount_remove_cart_cust_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='Cust_Id',
        ),
        migrations.AddField(
            model_name='order',
            name='User_Id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
