# Generated by Django 4.0.2 on 2023-01-22 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databases', '0016_remove_order_cust_id_order_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='Price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7),
            preserve_default=False,
        ),
    ]
