# Generated by Django 4.0.2 on 2023-01-22 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databases', '0017_order_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='Quantity',
            field=models.IntegerField(default=1, max_length=1),
            preserve_default=False,
        ),
    ]
