# Generated by Django 4.0.2 on 2023-01-22 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('databases', '0019_useraccount_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='Role',
        ),
    ]
