# Generated by Django 4.0.2 on 2023-01-22 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('databases', '0022_customer_user_id_restaurant_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Food_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='databases.menu')),
                ('Order_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='databases.order')),
            ],
        ),
    ]
