# Generated by Django 4.0.2 on 2023-01-23 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('databases', '0023_orderitems'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitems',
            name='Food_Id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordered_food', to='databases.menu'),
        ),
        migrations.AlterField(
            model_name='orderitems',
            name='Order_Id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_info', to='databases.order'),
        ),
    ]
