# Generated by Django 4.0.2 on 2023-01-25 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databases', '0027_remove_useraccount_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='Descr',
            field=models.CharField(default='abc', max_length=700),
            preserve_default=False,
        ),
    ]
