# Generated by Django 4.0.2 on 2023-03-01 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databases', '0028_menu_descr'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='Url',
            field=models.CharField(default='null', max_length=100),
            preserve_default=False,
        ),
    ]
