# Generated by Django 4.0.2 on 2023-03-01 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databases', '0029_menu_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='Url',
            field=models.CharField(max_length=300),
        ),
    ]
