# Generated by Django 4.0.2 on 2023-03-01 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databases', '0030_alter_menu_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='Url',
            field=models.CharField(default='null', max_length=300),
            preserve_default=False,
        ),
    ]
